data_dir : data
train_type : 
    if_train : true

prepare:
    train_split : 0.75
    shuffle : true
    seed : 6
    data : data/data.zip

train:
    weights : src/models/bottle_detection
    cfg : src/models/config.yaml
    data : data/dataset.yaml
    hyp : src/data/hyps/hyp.scratch-low.yaml
    epochs : 1
    batch_size : 2
    imgsz : 640
    rect : false
    resume : false
    nosave : false
    noval : false
    noautoanchor : false
    noplots : false
    evolve : 
    bucket : ''
    cache : ram
    image_weights : false
    device : cpu
    multi_scale : false
    single_cls : false
    optimizer : SGD # SGD, Adam, AdamW
    sync_bn : false
    workers : 8
    project : model
    name : ''
    exist_ok : false
    quad : false
    cos_lr : false
    label_smoothing : false
    patience : 100
    freeze: 
    - 10
    save_period : -1
    seed : 0
    local_rank : -1
    upload_dataset : false
    entity : 
    bbox_interval : -1
    artifact_alias : latest

export :
    weights : model/weights/best.pt
    include:
    - onnx

    

